version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
           echo "TODO: Install dependencies in the backend API"
           npm run api:install
      - run:
          name: Front-End Lint
          command: |
            echo "TODO: Lint the frontend"
          # npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            npm run frontend:build
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            npm run api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Set environment variables for EB
          command: |
            # Dynamically pass the CircleCI environment variables to Elastic Beanstalk
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME \
                    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
                    POSTGRES_HOST=$POSTGRES_HOST \
                    POSTGRES_DB=$POSTGRES_DB \
                    POSTGRES_DB_PORT=$POSTGRES_DB_PORT \
                    AWS_BUCKET=$AWS_BUCKET \
                    AWS_REGION=$AWS_REGION \
                    AWS_PROFILE=$AWS_PROFILE \
                    JWT_SECRET=$JWT_SECRET \
                    URL=$URL \
                    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                    AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - run:
          name: Deploy App
          command: |
            npm run deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
